/*
	SDZTimelineExample.m
	Provides example and test runs the service's proxy methods.
	Generated by SudzC.com
*/
#import "SDZTimelineExample.h"
#import "SDZTimeline.h"

@implementation SDZTimelineExample

- (void)run {
	// Create the service
	SDZTimeline* service = [SDZTimeline service];
	service.logging = YES;
	// service.username = @"username";
	// service.password = @"password";
	
    [UIApplication sharedApplication].networkActivityIndicatorVisible=TRUE;

	// Returns CXMLNode*. 
	[service GetTimeLineData:self action:@selector(GetTimeLineDataHandler:)];

	// Returns CXMLNode*. 
	//[service GetTimeLineDataWithRequest:self action:@selector(GetTimeLineDataWithRequestHandler:) PatientID: @"0"];
}

	

// Handle the response from GetTimeLineData.
		
- (void) GetTimeLineDataHandler: (id) value {

    [UIApplication sharedApplication].networkActivityIndicatorVisible=FALSE;

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the CXMLNode* result
		CXMLNode* result = (CXMLNode*)value;
	NSLog(@"GetTimeLineData returned the value: %@", result);
			
}
	

// Handle the response from GetTimeLineDataWithRequest.
		
- (void) GetTimeLineDataWithRequestHandler: (id) value {

	// Handle errors
	if([value isKindOfClass:[NSError class]]) {
		NSLog(@"%@", value);
		return;
	}

	// Handle faults
	if([value isKindOfClass:[SoapFault class]]) {
		NSLog(@"%@", value);
		return;
	}				
			

	// Do something with the CXMLNode* result
		CXMLNode* result = (CXMLNode*)value;
	NSLog(@"GetTimeLineDataWithRequest returned the value: %@", result);
			
}
	

@end
		